### ISSUE TITLE
Dynamic Client IP

### ISSUE THREAD

**Issue by legolas108** [Lochnair/blog#1]
In one of the client OpenVPN configuration files

`local 10.20.30.40`

is to be set to a local WAN IP.

Does that mean you require a static IP? Or how to deal with a dynamic IP as commonly provided by ISPs?

**Comment by Lochnair** [comment]
Not sure exactly how I had it configured when I wrote that post, but I'm guessing I let the modems NAT, and as a byproduct get a private static IP I could bind to.

Nowadays I prefer to keep one routing table per connection, and using fw marks to decide which one to use.

You can set the fwmark in the OpenVPN config with `mark <some number>`, and then you can choose the correct table like this:
```bash
ip rule add pref 10 fwmark 10 table 10
ip rule add pref 20 fwmark 20 table 20
```

You'd still need to create the routing tables with the right gateway for your ISP though. Depending on your provider you might get away with this:
```
# show protocols static table 10
 interface-route 0.0.0.0/0 {
     next-hop-interface eth1 {
     }
 }
```

**Comment by legolas108** [comment]
Sorry for late reply, and thanks much for your comment and for explaining how to use marks. Tried it, but ended up doing it differently. Got [a solution to work](https://serverfault.com/questions/977589/how-to-bond-two-multiple-internet-connections-for-increased-speed-and-failover) now without an EdgeRouter, just another Ubuntu Server box.
