### ISSUE TITLE
Patch file not found

### ISSUE THREAD

**Issue by fongcheche** [Lochnair/blog#3]
Hello! 

Thanks for your sharing. But I can't get the file Toolchain-Patches-SDK (https://dl.lochnair.net/Toolchains/Octeon/toolchain-patches-SDK-3.1.0p2-build34.tgz).

Could you please upload it again ?

**Comment by Lochnair** [comment]
Pretty sure I don't have access to that file anymore. Nowadays I use the source archives from here: https://github.com/MarvellEmbeddedProcessors/Octeon-Toolchain

**Comment by fongcheche** [comment]
Got it.
